### ISSUE TITLE
Renaming does not work in diagram editor

### ISSUE THREAD

**Issue by malinthar** [wso2/ballerina-plugin-vscode#164] opened 2022-01-20 08:17 UTC
**Description:**

Case 1

```ballerina
import ballerina/io;

# Person
#
# + name - Name of the person.  
# + age - Age of the person.
public type Person record {|
    string name;
    int age;
|};

# Greet someone
#
# + person - Person
function greet(Person person) {
    io:println("Hello " + person.name);
}

# Creates an returns a Person.
#
# + name - Name of the person. 
# + age - Age of the person.
# + return - A Person.
public function createPerson(string name, int age) returns Person {
    return {
        name: name,
        age: age
    };
}

public function main() {
    string name = "Alice"; //rename this variable using the diagram
    int age = 25;
    Person person1 = createPerson(name, age);
    greet(person1);
}

```
Try renaming the depicted variable. It does not rename all references.

Case 2

```ballerina
import ballerina/io;
import ballerina/io;
import ballerina/lang.'string;
import ballerina/websocket;

# Person
#
# + name - Field Description  
# + age - Age of the person.
public type Person record {|
    string name;
    int age;
|};

# Greet someone
#
# + person - Person
function greet(Person person) {
    io:println("Hello " + person.name);
}

// # Creates an returns a Person.
// #
// # + name - Name of the person. 
// # + age - Age of the person.
// # + return - A Person.
// public function createPerson(string name, int age) returns Person {
//     return {
//         firstname: name,
//         age: age
//     };
// }

public function main() {
    string name = "Alice";//rename this using the diagram
    int age = 25;
    Person person1 = createPerson(name, age);
    greet(person1);
}

function createPerson(string name, int age) returns Person {
    return {name: "", age: 0};
}

```
Try renaming the depicted variable. It does not rename any reference, and the following exception can be observed in the console.

```
[Error - 1:38:32 pm] Operation 'ballerinaDocument/syntaxTreeModify' failed! {uri: '/home/malintha/Documents/wso2/ballerina/projects/demo/main.bal', error: 'start 100, end 21, length 871'}
java.lang.IndexOutOfBoundsException: start 100, end 21, length 871
	at java.base/java.lang.AbstractStringBuilder.checkRange(AbstractStringBuilder.java:1716)
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:631)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:213)
	at io.ballerina.tools.text.StringTextDocument.apply(StringTextDocument.java:44)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaTreeModifyUtil.modifyTree(BallerinaTreeModifyUtil.java:202)
	at org.ballerinalang.langserver.extensions.ballerina.document.BallerinaDocumentService.syntaxTreeModify(BallerinaDocumentService.java:249)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.ballerinalang.langserver.extensions.AbstractExtendedLanguageServer.request(AbstractExtendedLanguageServer.java:120)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:127)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Affected Versions:**
SL-GA-rc1
plugin-version- v3.0.0-preview-m7

**Comment by prabushi** [comment] 2022-05-12 07:09
Renaming with reference feature is not available in the low-code editor.

**Comment by prabushi** [comment] 2022-05-12 07:16
Duplicate of https://github.com/wso2/ballerina-plugin-vscode/issues/155

**Closed by prabushi** 2022-05-12 07:16 UTC
Labels: Type/New Feature, Area/LowCode, MissingLCSupport
