### ISSUE TITLE
No syntax highlighting for the resource path parameters

### ISSUE THREAD

**Issue by nadeeshaan** [wso2/ballerina-plugin-vscode#162] opened 2022-01-19 08:44 UTC
**Description:**
Consider the highlighted section, where we need to highlight the square brackets, the type name and the variable name separately

<img width="682" alt="Screenshot 2022-01-19 at 14 08 19" src="https://user-images.githubusercontent.com/1329674/150094898-0aa9b6ba-95fd-4fc5-94fe-95ef5728d19e.png">

**Affected Versions:**
v3.0.0-preview-m7 at least

**Comment by gigara** [comment] 2022-05-06 04:03
Duplicate of https://github.com/wso2/ballerina-plugin-vscode/issues/141

**Closed** 2022-05-06 04:03 UTC
Labels: bug, Type/Bug, Priority/High, Resolution/Duplicate, Area/SemanticHighlighting
