### ISSUE TITLE
Improve test coverage of VSCode extension

### ISSUE THREAD

**Issue by prabushi** [wso2/ballerina-plugin-vscode#6] opened 2021-05-05 11:06 UTC
<a href="https://github.com/kaviththiranga"><img src="https://avatars.githubusercontent.com/u/1505855?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kaviththiranga](https://github.com/kaviththiranga)**
_Monday Feb 11, 2019 at 06:32 GMT_
_Originally opened as https://github.com/ballerina-platform/plugin-vscode/issues/44_

----

We have some several tests covering logic of detecting Ballerina distribution and spawning lang server up. But we have to improve the tests to capture other features.
For example: 

- [ ] Diagram rendering and editing
- [ ] Documentation preview
- [ ] API designer
- [ ] Network logs

**Comment by hevayo** [comment] 2023-01-20 05:14
Closing due to the issue is a generic topic and we have already improved testing from the point of the issue creation

**Closed by hevayo** 2023-01-20 05:14 UTC
Labels: Type/Task, ReleasePlan
