### ISSUE TITLE
Trying to add a listener statement but the save button won't activate

### ISSUE THREAD

**Issue by CharukaK** [wso2/ballerina-plugin-vscode#288] opened 2022-11-14 09:06 UTC
**Description:**
$subject

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**
Ballerina 2201.3.0

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by tharindulak** [comment] 2022-11-16 08:11
Since the issue is from the related to dependency resolution, created separate issue:https://github.com/wso2/ballerina-plugin-vscode/issues/302. Hence closing this.

**Closed by tharindulak** 2022-11-16 08:11 UTC
Labels: Type/Bug, Area/LowCode
