### ISSUE TITLE
The configurable view is not loading

### ISSUE THREAD

**Issue by kanushka** [wso2/ballerina-plugin-vscode#361] opened 2022-12-22 07:17 UTC
**Description:**

The configurable view should render if the user added a configurable to the source and tried to run from the UI button. But now the configurable view is keep loading without listing available configurable.

**Steps to reproduce:**

1. Add below sample code with a configurable
2. Click the run button in the UI

https://user-images.githubusercontent.com/24244523/209077344-834b9ef6-385c-45cc-9b6f-167311b0bc3b.mp4

CLI commands work without issue

- `bal run` with Config.toml
- `bal run -- -Cprefix="test"`

**Affected Versions:**
Plugin - ballerina-3.3.6-beta1.vsix

**Source code:**
```ballerina
import ballerina/http;

configurable string prefix = ?;

service http:Service /foo on new http:Listener(9090) {
    resource function get bar(int value) returns http:Response {
        http:Response response = new;

        if (value < 0) {
            response.statusCode = 400;
            response.setTextPayload("Incorrect ID value");
        } else {
            response.statusCode = 200;
            response.setTextPayload("Retrieved ID " + prefix + value.toString());
        }

        return response;
    }
}

```

**Comment by hevayo** [comment] 2023-04-26 18:51
We have disabled the config editor hence closing. Also the issue is fixed with 4.0.0

**Closed by hevayo** 2023-04-26 18:51 UTC
Labels: Type/Bug, Severity/Major, Area/VSCodeExtension, Team/VS Code Extension
